### ISSUE TITLE
The name of the ymp.yml file

### ISSUE THREAD

**Issue by hhollandmoritz** [epruesse/ymp#88]
While playing around with some new data in ymp, I have run into a persistent error
```Unrecognized statement in data config``` which turned out to be due to naming my ```.yml``` file ```sourdough.yml``` rather than ```ymp.yml```. From the tiny amount of googling I've done, I suspect this mistake is in part due to not being familiar with snakemake and perhaps if I was familiar, it would be a more obvious requirement. 

My questions are two-fold. 

1) Is there any way to allow the user the freedom of naming ```ymp.yml``` anything they would like?

2) Could this requirement be stated explicitly somewhere on the configuration page of the documentation? (https://ymp.readthedocs.io/en/latest/config.html)

Thanks!

**Comment by epruesse** [comment]
The idea was to have an analysis folder (e.g. `sourdough`) containing an `ymp.yml` that configures `YMP` for that folder. You can have multiple projects in there, e.g.:

```
projects:
   mg:
       data:
          - /data/sequencing/sourdough_metagenomes_20190503/mapping.csv
          - /data/sequencing/sourdough_metagenomes_20190704/mapping.csv
   tt:
      data:
          - /data/sequencing/sourdough_transcriptome_20190705/mapping.csv
```

You'd process those with

```
ymp make mg.trim_bbmap.assemble_metaspades....
ymp make tt.trim_bbmap.assemble_trinity...
```

If you had differently named `.yml` files, then you could do evil things. E.g. having two files configure a an `mg` project. That would lead to all manner of havoc.

I suppose I could add some more clear logging that tells you if you don't have an `ymp.yml`. The reason it doesn't complain immediately is that in theory you can run ymp from a generated subfolder to make specific files. Not sure that's still working though, TBH. I may drop that feature in favor of requiring that there is a `ymp.yml` in the folder you are running `ymp` in.

Does this make sense?
